# -*- coding: utf-8 -*-
"""Practica Unidad 1 Molinari - Sistemas Expertos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LcfnMkWjP2SJvKatlRDN_blrQ3RiMFZ3

# Desafío Individual: Sistema de Gestión de Obra Inteligente

## Contexto del Problema
Una empresa constructora está desarrollando una torre de gran altura y necesita automatizar dos procesos críticos para garantizar la seguridad y la eficiencia operativa:
* Evaluación de Riesgos en Obra (Lógica Deductiva): Determinar si es seguro continuar con las tareas de altura o excavación basándose en sensores climáticos y estructurales.
* Planificación de Maquinaria Pesada (Satisfacción de Restricciones): Asignar equipos (grúas, excavadoras) a zonas específicas del predio respetando límites de seguridad y espacio físico.

**Misión A:** Diagnóstico de Seguridad con expertaDebes programar un motor de inferencia que reciba datos de sensores y devuelva el nivel de riesgo del sitio. Este sistema actúa como un Cerebro Lógico para evitar accidentes.

Reglas a Implementar:
* **Riesgo Crítico** (Paro de Obra):  Si la velocidad del viento es $> 60\ km/h$ o si se detectan grietas en el suelo de fundación.
* **Riesgo Moderado** (Precaución): Si la velocidad del viento está entre $40\ km/h$ y $60\ km/h$ o si hay humedad extrema en zonas de excavación.
* **Bajo Riesgo** (Operación Normal): Si los vientos son $< 40\ km/h$ y no hay alertas estructurales activas.

**Consigna Técnica:** Utiliza el parámetro salience para asegurar que la regla de Riesgo Crítico se evalúe con la máxima prioridad ante cualquier otra condición.El sistema debe imprimir el diagnóstico final y la orden de seguridad correspondiente.

**Misión B:** Ubicación de Equipos con python-constraint

Debes encontrar la distribución óptima de 3 máquinas pesadas en 3 zonas de trabajo distintas. El sistema debe "podar" las opciones que violen las normativas de seguridad.

Restricciones (Reglas de Oro):
* **Grúa Torre:** Solo puede ubicarse en la Zona_Estable (debido a la necesidad de una base de hormigón reforzada).
* **Excavadora:** No puede ingresar a la Zona_Estrecha debido a sus dimensiones.
* **Hormigonera:** No puede estar en la misma zona que la Grúa Torre para evitar congestión de camiones.
* **Exclusividad:** Cada zona solo puede albergar una máquina a la vez para evitar colisiones.Consigna Técnica:Define las variables (Máquinas) y el dominio (Zonas de la obra).

Aplica las funciones de restricción para que el motor de búsqueda encuentre la única configuración válida.

### Mision A
"""

!pip install experta
!pip install --upgrade frozendict

from experta import *

class EstadoObra(Fact):
    """Datos capturados por sensores en el sitio"""
    pass

class MotorSeguridad(KnowledgeEngine):

    # REGLA 1: ALTO RIESGO (Prioridad 10)

    @Rule(OR(EstadoObra(viento=P(lambda v: v > 60)),
             EstadoObra(grietas=True)),
          salience=10)
    def riesgo_critico(self):
        print("\n--- DIAGNÓSTICO FINAL ---")
        print("RIESGO: ALTO")
        print("ORDEN: DETENER OBRA")
        self.halt()

    # REGLA 2: RIESGO MODERADO (Prioridad 5)
    @Rule(OR(EstadoObra(viento=P(lambda v: 40 <= v <= 60)),
             EstadoObra(humedad_extrema=True)),
          salience=5)
    def riesgo_moderado(self):
        print("\n--- DIAGNÓSTICO FINAL ---")
        print("RIESGO: MODERADO")
        print("ORDEN: REFORZAR LA ESTRUCTURA / PRECAUCIÓN")

    # REGLA 3: BAJO RIESGO (Prioridad 1)
    @Rule(EstadoObra(viento=P(lambda v: v < 40),
                     grietas=False,
                     humedad_extrema=False),
          salience=1)
    def bajo_riesgo(self):
        print("\n--- DIAGNÓSTICO FINAL ---")
        print("RIESGO: BAJO")
        print("ORDEN: NORMAL, SEGUIR CON LA CONSTRUCCIÓN")


engine = MotorSeguridad()
engine.reset()

#EJEMPLO
# Datos: viento de 65 km/h y presencia de grietas
datos = EstadoObra(viento=20, grietas=False, humedad_extrema=False)

engine.declare(datos)
engine.run()

"""### Mision B"""

!pip install python-constraint

from constraint import *

def planificar_maquinaria():
    problem = Problem()
    # 1) Definir máquinas (variables) y zonas (dominios)
    maquinas = ["Grua_Torre", "Excavadora", "Hormigonera"]
    zonas= ["Estable", "Estrecha", "Comun"]

    problem.addVariables(maquinas, zonas)

    # 2) Restricciones
    # Restriccion 1: Exclusividad (1 máquina por zona)
    problem.addConstraint(AllDifferentConstraint())

    #Restriccion 2: Grúa torre unicamente en zona estable
    problem.addConstraint(lambda gt: gt == "Zona_Estable", ["Grua_Torre"])

    #Restriccion 3: Prohibido Excavadora en zona estrecha
    problem.addConstraint(lambda ex: ex != "Zona_Estrecha", ["Excavadora"])

    #Restriccion 4: Hormigonera NO puede estar con la Grúa

    problem.addConstraint(lambda ho, gt: ho != gt, ("Hormigonera", "Grua_Torre"))

    # 3) Resolución del problema

    soluciones = problem.getSolutions()
    print(f"Se encontraron {len(soluciones)} configuraciones seguras:")
    for i, sol in enumerate(soluciones, 1):
        print(f"Opción {i}: {sol}")

planificar_maquinaria()

"""## Parámetros de Entrega y Evaluación
El entregable debe cumplir con lo siguiente:

* **Justificación Funcional:** Debes explicar en celdas de texto por qué el modelo de grafos y árboles es superior a una simple lista de if/else para este problema.
* **Documentación:** El código debe estar respaldado por una explicación de cómo opera el motor de inferencia en cada caso.

*Tener en cuenta que se evalua proceso y no resultado. Acordarse de justificar las elecciones en cada caso.*
"""